apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  destination:
    name: ''
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 35.3.0
    chart: kube-prometheus-stack
  sources: []
  project: default
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: false
    syncOptions:
      - CreateNamespace=true
